# Generated by Django 3.2 on 2021-04-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0002_auto_20210429_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_display',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_display',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
