# Generated by Django 3.2 on 2021-04-30 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0004_subsection_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='section_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infos.section'),
        ),
    ]
