# Generated by Django 3.2 on 2021-04-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0005_alter_paragraph_section_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsection',
            name='paragraph',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
